name: tp1-server
networks:
  amazon-network:
    external: 'true'
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  clientHandler:
    container_name: clientHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: client_handler:latest
    networks:
    - amazon-network
    volumes:
    - ./server/clientHandler/config.ini:/config.ini
version: '3.9'
